### ISSUE TITLE
Chapitre 10

### ISSUE THREAD

**Issue by xavierforestier** [Jimskapt/rust-book-fr#235]
Au début du chapitre 10 dans le premier exemple "largest number" est traduit en "nombre le plus gros" => le plus grand serait plus français :)

Dans 10.3
Plusieurs encarts avec les exemples d'erreurs de compilations sont en double : une fois non-formatée dans le texte et une seconde fois avec le formatage code.

> pour déterminer **quelle** référence que nous allons retourner sera toujours en vigueur

> pour déterminer **que la** référence que nous allons retourner sera toujours en vigueur

**Comment by Jimskapt** [comment]
Bonjour @xavierforestier, merci d'avoir pris le temps de nous signaler ces problèmes !

> Au début du chapitre 10 dans le premier exemple "largest number" est traduit en "nombre le plus gros" => le plus grand serait plus français :)

Ah oui effectivement c'est grossophobe, pas de cela ici ! 😁
D'ailleurs, on a corrigé instinctivement la traduction par la suite.
J'ai donc intégré votre suggestion de modification dans #106, merci !

> Plusieurs encarts avec les exemples d'erreurs de compilations sont en double : une fois non-formatée dans le texte et une seconde fois avec le formatage code.

Oula oui c'est problème que j'avais identifié et corrigé dans a2893fa804dc89cbd8b4034c1590e68656d55163.
Une partie du travail pour le 10-03 a déjà été fait, mais on dirait que la correction des liens vers `[...]/listings/[...]` est passé _sous le radar_.
J'ai donc fait des suggestions de correction dans #120
Merci du signalement !

> > pour déterminer **que la** référence que nous allons retourner sera toujours en vigueur

Effectivement, suggestion de correction intégrée elle aussi dans #120 😉
