### ISSUE TITLE
Suggestion: Translate "privacy" as "visibilité"

### ISSUE THREAD

**Issue by joeljpresent** [Jimskapt/rust-book-fr#243]
I think we should translate the term *privacy* as *visibilité* rather than *protection* when referring to the scope where an item can be accessed.
The term *visibilité* is used by many French developers to describe this concept (especially in Java, but also in Python, PHP, C++…) whereas the term *protection* is very vague and not eloquent.

Since the term *privacy* mostly occurs in the pages I'm about to proofread, I will be able to make the changes myself within the proofreading.

**Comment by Jimskapt** [comment]
It's ok for me, both translations seems OK for me so I agree we can change the translation `privacy` from `protection` to `visibilité` 😉
