### ISSUE TITLE
Chapite 3.2 : Oubli de traduction

### ISSUE THREAD

**Issue by Azel-ytof** [Jimskapt/rust-book-fr#253]
Hi !

I'm just reading the book to learn Rust.

I just found something in the chapter 3.2, in the subpart "Numerical operation".
Indeed, there are "contains a" and "list of all operators that Rust provides. -->".

Maybe a copy/paste that went wrong ?

--- --- --- --- --- ---

Bonjour,

Je suis en train de suivre le book que vous avez traduit afin d'apprendre Rust.

Je viens de remarquer que vous avez omis deux lignes dans la sous-partie "Les opérations numériques" :
- contains a
- list of all operators that Rust provides. -->

Peut-être un copier/coller qui ne s'est pas bien déroulé ?

**Comment by fgx-dev** [comment]
#255

**Comment by Jimskapt** [comment]
Thank you @Azel-ytof  for your alert, and thank you @fgx-dev for your fix !
