### ISSUE TITLE
Coquille dans Ch. 3.5 (boucles for)

### ISSUE THREAD

**Issue by kouma** [Jimskapt/rust-book-fr#259]
Bonjour et merci pour votre travail précieux.

Je remonte une petite coquille dans le chapitre 3.5 au paragraphe sur les boucles for :
"Par exemple, dans le code de l'encart 3-4, si vous changez la définition du tableau a pour qu'il **stocle** quatre éléments"

A l'évidence, c'est *stocke* qu'il faut lire.

Bien à vous, je continue ma lecture.

**Comment by kouma** [comment]
Au temps pour moi, je me basais sur la version en ligne, la coquille a été corrigée sur le repo. Désolé pour le dérangement, je ferai plus attention la prochaine fois.

**Comment by Jimskapt** [comment]
Merci quand même, @kouma ! 😄

Je viens de mette à jour la "version en ligne" 😉
