### ISSUE TITLE
Typo / Error in chapter 3 / 02

### ISSUE THREAD

**Issue by paulhenri** [Jimskapt/rust-book-fr#261]
Hi,

I think there is a small typo in the thrid chapter. Just after "Opérations numériques" and the code block, there is still english text :
"
contains a
list of all operators that Rust provides. -->

"

Thank you for your work 👍 
Paul-H

![2021-03-26 08_34_19-Les types de données - Le langage de programmation Rust – Brave](https://user-images.githubusercontent.com/426600/112597926-20729a80-8e0e-11eb-84b1-409b13f97465.png)

**Comment by Jimskapt** [comment]
Hello @paulhenri, and thank you for your report !

This problem has been already signaled in #253 and fixed by #255, several weeks ago 😉

I just need to update a new release of the book in `gh-pages` branch. I think I will do it in a couple of days/hours 😉

See you next time !

**Comment by Jimskapt** [comment]
`gh-pages` has been updated 😉
