### ISSUE TITLE
*crate* gender ?

### ISSUE THREAD

**Issue by Jimskapt** [Jimskapt/rust-book-fr#37]
I'm currently *self-proofreading* my translation of ch02-00.

There is a massive use of *crate(s)* term. On first, I was thinking `le crate` (a masculine term) was more relevant than `la crate` (a feminine term), but now i'm thinking the opposite : if we translate literally, it should be more convenient to translate it with *la caisse* than *le caisse*, right ?
At first, @quadrifoglio has translated that with `la crate`.

I think I need your external point of view, @joeljpresent, what do you think about it ?

**Comment by joeljpresent** [comment]
I tend to use it as a feminine word: *la crate* sounds more natural than *le crate*.

**Comment by Jimskapt** [comment]
OK, I think we all agree. This change was reported in commit e5ab678a90df4039a7186be7f537e65a8eb769b7 on `FR-ch02-00` branch.
Thank you !
