### ISSUE TITLE
retour de fonction et son exemple par copie, référence ou ??

### ISSUE THREAD

**Issue by syapk** [Jimskapt/rust-book-fr#371]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:

https://jimskapt.github.io/rust-book-fr/ch10-01-syntax.html

Description of the problem:

**_fn le_plus_grand<T>(liste: &[T]) -> T {_
_Cette définition se lit comme ceci : la fonction le_plus_grand est générique en fonction du_ _type T. Cette fonction a un paramètre qui s'appelle liste, qui est une slice de valeurs de type_ _T. Cette fonction le_plus_grand va retourner une référence vers la valeur du même type T._**

Suggested fix:
retour par copie plutot??
et encore merci pour la traduction

**Comment by Jimskapt** [comment]
Oui effectivement, il s'agit d'un oubli d'actualisation de la traduction dans mon commit 1e092cf6afb499aaa0feb9070b8fb1ad5fb3768b !
Je corrige cela, merci du signalement ! 😊
