### ISSUE TITLE
translate error

### ISSUE THREAD

**Issue by syapk** [Jimskapt/rust-book-fr#372]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:
https://jimskapt.github.io/rust-book-fr/ch15-05-interior-mutability.html

Description of the problem:
Rc<T> permet d'avoir plusieurs propriétaires pour une même donnée ; `Rc<T>` et RefCell<T> n'ont qu'un seul propriétaire.

Rc<T> enables multiple owners of the same data; `Box<T>` and RefCell<T> have single owners.

Suggested fix:
Rc<T> permet d'avoir plusieurs propriétaires pour une même donnée ; `Box<T>` et RefCell<T> n'ont qu'un seul propriétaire.

**Comment by Jimskapt** [comment]
Nice catch, thank you, @syapk ! 👍
