### ISSUE TITLE
lifetime traduction

### ISSUE THREAD

**Issue by vincentserpoul** [Jimskapt/rust-book-fr#64]
Bonjour,

J'ai une interrogation sur la traduction de lifetime.
En francais, la duree de vie est effectivement une quantite de temps, qui ne prends pas en compte la temporalite, sans debut et sans fin.
A moins de me tromper (ce qui est possible, je ne pratique rust que depuis peu de temps), j'ai l'impression que lifetime contient une notion de debut et de fin.
2 choses peuvent avoir la meme duree de vie et pourtant ne pas avoir lieu au meme moment, ce qui n'est pas le cas des lifetimes, car un lifetime est defini avec un debut et une fin.
J'avais pense a "moment de vie" ou "temps de vie" comme traduction.

Qu'en pensez vous ?

**Comment by joeljpresent** [comment]
Le terme “[durée de vie][duree-google]” est couramment utilisé pour traduire le terme anglais “lifetime” dans le cas de variables − bien plus que “moment de vie” ou “temps de vie” qui sont beaucoup moins courants et pas forcément plus clairs.

Le terme “durée” peut désigner un espace de temps entre deux évènements : 

>  Espace de temps, période mesurable pendant lequel a lieu un événement, un phénomène, une action, un état ; temps : *La route est déviée pendant la durée des travaux.*
> [Larousse][duree-larousse]

Dans l'exemple donné, *la durée des travaux* fait référence à la période commençant au début des travaux et se terminant à la fin des travaux ; on peut bien considérer une durée comme étant une période.

[duree-google]: https://www.google.com/search?q=dur%C3%A9e+de+vie+d%27une+variable
[duree-larousse]: https://www.larousse.fr/dictionnaires/francais/dur%c3%a9e/27045?q=dur%c3%a9e#26907

**Comment by vincentserpoul** [comment]
Merci pour cette explication concise et claire.
