### ISSUE TITLE
Translation of “slice”

### ISSUE THREAD

**Issue by joeljpresent** [Jimskapt/rust-book-fr#98]
Before I can proofread Chapter 4 and push my translation of Chapter 05-01, we need to agree on a translation for *slice*.

Chapter 04-00 retains the English term, `slice`, which is fine with me.
Chapter 04-03 calls it `découpage`, which is a term that I find unclear because it sounds more like the action of cutting rather than the result of the cutting.
I would prefer `tranche` because it sounds clearer.

**Comment by Jimskapt** [comment]
`Une tranche de chaîne de caractères` looks weird to me (and its makes me hungry, but this is another issue 😆 )

Furthermore, I think that `un découpage de chaîne de caractères` can also be understood as the result of the slicing, don't you ?

**Comment by joeljpresent** [comment]
IMO, `un découpage de chaîne de caractères` is not less weird, and I have another issue with this translation: it makes it look like string slices are always the result of slicing while this is usually not true in Rust.
*String slice* is a generic term for a `&str`, which is usually obtained from a literal (`"hello world"`) or from a full String (`string.as_str()`). It would sound really strange to call them `découpages` (albeit `tranches` would sound strange too).
Since either translation seems inadequate, I think we should keep `slice` as an anglicism, which is what many tutorials do.

**Comment by Jimskapt** [comment]
Are you agree with one of this translations of `a slice of an array` ?

1. `un morceau de tableau`
2. `un échantillon de tableau`
3. `un extrait de tableau`
4. `une extraction de tableau`
5. `une partie de tableau`

Otherwise, we will fall back to the anglicism.

**Comment by Jimskapt** [comment]
I this case, we will keep the Anglicism `slice`.

Keep in mind that it will cause os some troubles when we want to search & replace this term, because it is the same as (commented) English text.

It's a lot of work so I will let you change it anywere.

**Comment by Jimskapt** [comment]
Hi @joeljpresent, do you say that `slice` should be used to feminine or masculine form ? I'm curently use it a lot on ch10 with feminine form : `c'est une slice de valeurs de type T`.

**Comment by joeljpresent** [comment]
Let's use it as a feminine word.
